<?php

namespace IikoTransport\Entity\Order;

class Exception extends \IikoTransport\Exception {
	const GENDER_IS_NOT_IN_WHITE_LIST = 1;
	const PAYMENT_TYPE_KIND_IS_NOT_IN_WHITE_LIST = 2;
	const ITEM_TYPE_IS_NOT_IN_WHITE_LIST = 3;
	const ORDER_SERVICE_TYPE_IS_NOT_IN_WHITE_LIST = 4;
	
	const PHONE_IS_NOT_SET = 6;
	const ITEMS_IS_NOT_SET = 7;
	
	const PRODUCT_ID_OF_PRODUCT_IS_NOT_SET = 8;
	const AMOUNT_OF_PRODUCT_IS_NOT_SET = 9;
	
	const PRODUCT_ID_OF_MODIFIER_IS_NOT_SET = 10;
	const AMOUNT_OF_MODIFIER_IS_NOT_SET = 11;

	const ID_OF_COMBO_IS_NOT_SET = 12;
	const NAME_OF_COMBO_IS_NOT_SET = 13;
	const AMOUNT_OF_COMBO_IS_NOT_SET = 14;
	const PRICE_OF_COMBO_IS_NOT_SET = 15;
	const SOURCE_ID_OF_COMBO_IS_NOT_SET = 16;

	const PAYMENT_SUM_IS_NOT_SET = 17;
	const PAYMENT_TYPE_ID_IS_NOT_SET = 18;
	const IS_PROCESSED_EXTERNALLY_IS_NOT_SET = 19;

	const SEARCH_SCOPE_IS_NOT_IN_WHITE_LIST = 20;
	const PAYMENT_ADDITIONAL_DATA_TYPE_IS_NOT_IN_WHITE_LIST = 21;
	const PAYMENT_ADDITIONAL_DATA_CREDENTIAL_IS_NOT_SET = 22;

	const ONE_OF_FIELD_ORDERTYPEID_OR_ORDERSERVICETYPE_REQUIRED = 23;

	const TRACK_IS_NOT_SET = 24;

	const STREET_IS_NOT_SET = 25;
	const HOUSE_IS_NOT_SET = 26;

	const LATITUDE_IS_NOT_SET = 27;
	const LONGITUDE_IS_NOT_SET = 28;

	const COUNT_IS_NOT_SET = 29;
	const SPLIT_BETWEEN_PERSONS_IS_NOT_SET = 30;
}